
STEGOLIKE_CHARSET = "abcdefghijklmnopqrstuvwxyz0123456789 '.,:?!/-+=<>$_*()@#|%&[]{}^"
STEGOLIKE_BITS_X_CHAR = 6
STEGOLIKE_CHARS_X_INTERACTION = 2
STEGOLIKE_AVAILABLE_INTERACTIONS = 3
STEGOLIKE_NUM_MESSAGES = (len(STEGOLIKE_CHARSET) ** STEGOLIKE_CHARS_X_INTERACTION) / STEGOLIKE_AVAILABLE_INTERACTIONS + 1

STEGOLIKE_TWITTER_CONSUMER_KEY = "XXX"
STEGOLIKE_TWITTER_CONSUMER_SECRET = "XXX"
STEGOLIKE_TWITTER_KEY = "XXX"
STEGOLIKE_TWITTER_SECRET = "XXX"



