
STEGOLIKE_CHARSET = "abcdefghijklmnopqrstuvwxyz0123456789 '.,:?!/-+=<>$-_*()@#|%&[]{}"
STEGOLIKE_BITS_X_CHAR = 6
STEGOLIKE_CHARS_X_INTERACTION = 2
STEGOLIKE_NUM_MESSAGES = len(STEGOLIKE_CHARSET) ** STEGOLIKE_CHARS_X_INTERACTION 


