CHARSET = "abcdefghijklmnopqrstuvwxyz0123456789 '.,:?!/-+=<>$_*()@#|%&[]{}^"
BITS_X_CHAR = 6
CHARS_X_INTERACTION = 2
AVAILABLE_INTERACTIONS = 1
NUM_MESSAGES = (len(CHARSET) ** CHARS_X_INTERACTION) / \
    AVAILABLE_INTERACTIONS + 1

TWITTER_CONSUMER_KEY = 'XXX'
TWITTER_CONSUMER_SECRET = 'XXX'
TWITTER_KEY = 'XXX'
TWITTER_SECRET = 'XXX'
